version: "3.8"

services:
  freeipa:
    image: freeipa/freeipa-server:rocky-9
    container_name: freeipa-server
    hostname: ${IPA_SERVER_HOSTNAME}
    environment:
      - IPA_SERVER_HOSTNAME=${IPA_SERVER_HOSTNAME}
      - IPA_DOMAIN=${IPA_DOMAIN}
      - IPA_REALM=${IPA_REALM}
      - IPA_ADMIN_PASSWORD=${IPA_ADMIN_PASSWORD}
      - IPA_PASSWORD=${IPA_PASSWORD}
      - DEBUG_TRACE=${DEBUG_TRACE}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - freeipa-data:/data
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
    network_mode: "host"

volumes:
  freeipa-data:
